import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    dashboard: 'Dashboard',
    profile: 'Profile',
    cropAdvice: 'Crop Advice',
    weather: 'Weather',
    marketPrices: 'Market Prices',
    learningHub: 'Learning Hub',
    chatbot: 'Help & Support',
    schemeFinder: 'Scheme Finder',
    feedback: 'Feedback',
    welcome: 'Welcome to Kisaan Sethu',
    login: 'Login',
    phoneNumber: 'Phone Number',
    otp: 'Enter OTP',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    name: 'Name',
    location: 'Location',
    farmSize: 'Farm Size (acres)',
    soilType: 'Soil Type',
    save: 'Save',
    submit: 'Submit',
    // Dashboard
    welcomeBack: 'Welcome back',
    getCropAdvice: 'Get Crop Advice',
    weatherAlerts: 'Weather Alerts',
    askAiHelper: 'Ask AI Helper',
    weatherUpdate: 'Weather Update',
    recentActivity: 'Recent Activity',
    heavyRainfall: 'Heavy rainfall expected in your area',
    newRecommendations: 'New recommendations for wheat cultivation',
    // Profile
    updateProfile: 'Update Profile',
    completeProfile: 'Complete Your Profile',
    helpPersonalized: 'Help us provide personalized farming advice',
    enterFullName: 'Enter your full name',
    cityState: 'City, State',
    enterFarmSize: 'Enter farm size in acres',
    selectSoilType: 'Select soil type',
    saving: 'Saving...',
    // Crop Advice
    aiCropAdvice: 'AI Crop Advice',
    personalizedRecommendations: 'Get personalized farming recommendations based on your profile',
    askFarmingQuestion: 'Ask your farming question',
    exampleQuestion: 'e.g., What is the best time to plant wheat in my area?',
    gettingAdvice: 'Getting Advice...',
    getAdvice: 'Get Advice',
    quickQuestions: 'Quick Questions',
    aiRecommendation: 'AI Recommendation',
    whatCropsPlant: 'What crops should I plant this season?',
    improveSoilFertility: 'How to improve soil fertility?',
    bestIrrigation: 'Best irrigation practices for my farm?',
    pestControl: 'Pest control recommendations',
    organicFarming: 'Organic farming techniques',
    // Weather
    weatherForecast: 'Weather Forecast',
    updating: 'Updating...',
    refresh: 'Refresh',
    weatherAlertsTitle: 'Weather Alerts',
    monitorWeather: 'Monitor weather conditions closely for optimal farming decisions.',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    rainfall: 'Rainfall',
    detailedWeather: 'Detailed Weather & Farming Recommendations',
    unableToLoad: 'Unable to load weather data. Please try refreshing.',
    // Market Prices
    marketAnalysis: 'Market Analysis & Recommendations',
    marketTips: 'Market Tips',
    checkPricesRegularly: 'Check prices regularly before harvesting',
    considerNearbyMarkets: 'Consider nearby markets for better rates',
    storeCrops: 'Store crops when prices are low, sell when high',
    joinFarmerGroups: 'Join farmer groups for collective bargaining',
    // Learning Hub
    expandKnowledge: 'Expand your farming knowledge with expert content',
    searchArticles: 'Search articles and videos...',
    allTopics: 'All Topics',
    cropManagement: 'Crop Management',
    soilHealth: 'Soil Health',
    irrigation: 'Irrigation',
    pestControlCategory: 'Pest Control',
    organicFarmingCategory: 'Organic Farming',
    watch: 'Watch',
    read: 'Read',
    noContentFound: 'No content found matching your search criteria.',
    // Chatbot
    aiFarmingAssistant: 'AI Farming Assistant',
    instantHelp: 'Get instant help with your farming questions',
    askAnything: 'Ask me anything about farming...',
    controlPestsNaturally: 'How to control pests naturally?',
    bestIrrigationPractices: 'Best irrigation practices',
    governmentSchemes: 'Government schemes for farmers',
    soilHealthImprovement: 'Soil health improvement tips',
    // Scheme Finder
    governmentSchemesTitle: 'Government Schemes',
    findSubsidies: 'Find subsidies and schemes available for farmers in',
    searchSchemes: 'Search schemes...',
    allCategories: 'All Categories',
    financialSupport: 'Financial Support',
    insurance: 'Insurance',
    technicalSupport: 'Technical Support',
    equipmentSubsidy: 'Equipment Subsidy',
    eligibility: 'Eligibility',
    benefits: 'Benefits',
    howToApply: 'How to Apply',
    viewDetails: 'View Details',
    visitOfficialPage: 'Visit Official Page',
    active: 'Active',
    noSchemesFound: 'No schemes found matching your criteria.',
    // Feedback
    helpImprove: 'Help us improve Kisaan Sethu with your valuable feedback',
    overallRating: 'Overall Rating',
    poor: 'Poor',
    fair: 'Fair',
    good: 'Good',
    veryGood: 'Very Good',
    excellent: 'Excellent',
    feedbackCategory: 'Feedback Category',
    selectCategory: 'Select a category',
    yourFeedback: 'Your Feedback',
    shareExperience: 'Please share your experience, issues, or comments...',
    suggestionsImprovement: 'Suggestions for Improvement (Optional)',
    whatFeatures: 'What features would you like to see? How can we make the app better?',
    submitting: 'Submitting...',
    submitFeedback: 'Submit Feedback',
    needDirectSupport: 'Need Direct Support?',
    helpline: 'Helpline: 1800-XXX-XXXX (Toll Free)',
    email: 'Email: support@kisaansethu.gov.in',
    available: 'Available: 24/7 for farmer support',
    thankYou: 'Thank You!',
    feedbackSubmitted: 'Your feedback has been submitted successfully. We appreciate your input and will use it to improve Kisaan Sethu.',
    submitAnother: 'Submit Another Feedback',
    // Common
    menu: 'Menu',
    changePhoneNumber: 'Change phone number',
    sentTo: 'Sent to',
    perQuintal: 'per quintal',
    minRead: 'min read',
    min: 'min'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    cropAdvice: 'फसल सलाह',
    weather: 'मौसम',
    marketPrices: 'बाजार भाव',
    learningHub: 'शिक्षा केंद्र',
    chatbot: 'सहायता',
    schemeFinder: 'योजना खोजक',
    feedback: 'प्रतिक्रिया',
    welcome: 'किसान सेतु में आपका स्वागत है',
    login: 'लॉगिन',
    phoneNumber: 'फोन नंबर',
    otp: 'OTP दर्ज करें',
    sendOtp: 'OTP भेजें',
    verifyOtp: 'OTP सत्यापित करें',
    name: 'नाम',
    location: 'स्थान',
    farmSize: 'खेत का आकार (एकड़)',
    soilType: 'मिट्टी का प्रकार',
    save: 'सेव करें',
    submit: 'जमा करें',
    // Dashboard
    welcomeBack: 'वापसी पर स्वागत है',
    getCropAdvice: 'फसल सलाह लें',
    weatherAlerts: 'मौसम चेतावनी',
    askAiHelper: 'AI सहायक से पूछें',
    weatherUpdate: 'मौसम अपडेट',
    recentActivity: 'हाल की गतिविधि',
    heavyRainfall: 'आपके क्षेत्र में भारी बारिश की संभावना',
    newRecommendations: 'गेहूं की खेती के लिए नई सिफारिशें',
    // Profile
    updateProfile: 'प्रोफाइल अपडेट करें',
    completeProfile: 'अपना प्रोफाइल पूरा करें',
    helpPersonalized: 'व्यक्तिगत कृषि सलाह प्रदान करने में हमारी सहायता करें',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    cityState: 'शहर, राज्य',
    enterFarmSize: 'एकड़ में खेत का आकार दर्ज करें',
    selectSoilType: 'मिट्टी का प्रकार चुनें',
    saving: 'सेव हो रहा है...',
    // Crop Advice
    aiCropAdvice: 'AI फसल सलाह',
    personalizedRecommendations: 'अपनी प्रोफाइल के आधार पर व्यक्तिगत कृषि सिफारिशें प्राप्त करें',
    askFarmingQuestion: 'अपना कृषि प्रश्न पूछें',
    exampleQuestion: 'जैसे, मेरे क्षेत्र में गेहूं बोने का सबसे अच्छा समय क्या है?',
    gettingAdvice: 'सलाह मिल रही है...',
    getAdvice: 'सलाह लें',
    quickQuestions: 'त्वरित प्रश्न',
    aiRecommendation: 'AI सिफारिश',
    whatCropsPlant: 'इस सीजन में कौन सी फसल लगानी चाहिए?',
    improveSoilFertility: 'मिट्टी की उर्वरता कैसे बढ़ाएं?',
    bestIrrigation: 'मेरे खेत के लिए सबसे अच्छी सिंचाई प्रथाएं?',
    pestControl: 'कीट नियंत्रण की सिफारिशें',
    organicFarming: 'जैविक खेती की तकनीकें',
    // Weather
    weatherForecast: 'मौसम पूर्वानुमान',
    updating: 'अपडेट हो रहा है...',
    refresh: 'रिफ्रेश करें',
    weatherAlertsTitle: 'मौसम चेतावनी',
    monitorWeather: 'इष्टतम कृषि निर्णयों के लिए मौसम की स्थिति की बारीकी से निगरानी करें।',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    windSpeed: 'हवा की गति',
    rainfall: 'वर्षा',
    detailedWeather: 'विस्तृत मौसम और कृषि सिफारिशें',
    unableToLoad: 'मौसम डेटा लोड करने में असमर्थ। कृपया रिफ्रेश करने का प्रयास करें।',
    // Market Prices
    marketAnalysis: 'बाजार विश्लेषण और सिफारिशें',
    marketTips: 'बाजार सुझाव',
    checkPricesRegularly: 'फसल काटने से पहले नियमित रूप से कीमतों की जांच करें',
    considerNearbyMarkets: 'बेहतर दरों के लिए आस-पास के बाजारों पर विचार करें',
    storeCrops: 'कीमतें कम होने पर फसल स्टोर करें, ज्यादा होने पर बेचें',
    joinFarmerGroups: 'सामूहिक सौदेबाजी के लिए किसान समूहों में शामिल हों',
    // Learning Hub
    expandKnowledge: 'विशेषज्ञ सामग्री के साथ अपने कृषि ज्ञान का विस्तार करें',
    searchArticles: 'लेख और वीडियो खोजें...',
    allTopics: 'सभी विषय',
    cropManagement: 'फसल प्रबंधन',
    soilHealth: 'मिट्टी का स्वास्थ्य',
    irrigation: 'सिंचाई',
    pestControlCategory: 'कीट नियंत्रण',
    organicFarmingCategory: 'जैविक खेती',
    watch: 'देखें',
    read: 'पढ़ें',
    noContentFound: 'आपके खोज मानदंडों से मेल खाने वाली कोई सामग्री नहीं मिली।',
    // Chatbot
    aiFarmingAssistant: 'AI कृषि सहायक',
    instantHelp: 'अपने कृषि प्रश्नों के लिए तुरंत सहायता प्राप्त करें',
    askAnything: 'कृषि के बारे में मुझसे कुछ भी पूछें...',
    controlPestsNaturally: 'प्राकृतिक रूप से कीटों को कैसे नियंत्रित करें?',
    bestIrrigationPractices: 'सबसे अच्छी सिंचाई प्रथाएं',
    governmentSchemes: 'किसानों के लिए सरकारी योजनाएं',
    soilHealthImprovement: 'मिट्टी के स्वास्थ्य में सुधार के सुझाव',
    // Scheme Finder
    governmentSchemesTitle: 'सरकारी योजनाएं',
    findSubsidies: 'में किसानों के लिए उपलब्ध सब्सिडी और योजनाएं खोजें',
    searchSchemes: 'योजनाएं खोजें...',
    allCategories: 'सभी श्रेणियां',
    financialSupport: 'वित्तीय सहायता',
    insurance: 'बीमा',
    technicalSupport: 'तकनीकी सहायता',
    equipmentSubsidy: 'उपकरण सब्सिडी',
    eligibility: 'पात्रता',
    benefits: 'लाभ',
    howToApply: 'आवेदन कैसे करें',
    viewDetails: 'विवरण देखें',
    visitOfficialPage: 'आधिकारिक पृष्ठ पर जाएं',
    active: 'सक्रिय',
    noSchemesFound: 'आपके मानदंडों से मेल खाने वाली कोई योजना नहीं मिली।',
    // Feedback
    helpImprove: 'अपनी मूल्यवान प्रतिक्रिया के साथ किसान सेतु को बेहतर बनाने में हमारी सहायता करें',
    overallRating: 'समग्र रेटिंग',
    poor: 'खराब',
    fair: 'ठीक',
    good: 'अच्छा',
    veryGood: 'बहुत अच्छा',
    excellent: 'उत्कृष्ट',
    feedbackCategory: 'प्रतिक्रिया श्रेणी',
    selectCategory: 'एक श्रेणी चुनें',
    yourFeedback: 'आपकी प्रतिक्रिया',
    shareExperience: 'कृपया अपना अनुभव, समस्याएं या टिप्पणियां साझा करें...',
    suggestionsImprovement: 'सुधार के लिए सुझाव (वैकल्पिक)',
    whatFeatures: 'आप कौन सी सुविधाएं देखना चाहेंगे? हम ऐप को कैसे बेहतर बना सकते हैं?',
    submitting: 'जमा हो रहा है...',
    submitFeedback: 'प्रतिक्रिया जमा करें',
    needDirectSupport: 'प्रत्यक्ष सहायता चाहिए?',
    helpline: 'हेल्पलाइन: 1800-XXX-XXXX (टोल फ्री)',
    email: 'ईमेल: support@kisaansethu.gov.in',
    available: 'उपलब्ध: किसान सहायता के लिए 24/7',
    thankYou: 'धन्यवाद!',
    feedbackSubmitted: 'आपकी प्रतिक्रिया सफलतापूर्वक जमा कर दी गई है। हम आपके इनपुट की सराहना करते हैं और इसका उपयोग किसान सेतु को बेहतर बनाने के लिए करेंगे।',
    submitAnother: 'एक और प्रतिक्रिया जमा करें',
    // Common
    menu: 'मेनू',
    changePhoneNumber: 'फोन नंबर बदलें',
    sentTo: 'को भेजा गया',
    perQuintal: 'प्रति क्विंटल',
    minRead: 'मिनट पढ़ें',
    min: 'मिनट'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'hi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    toggleLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
